set( CCOS_VERSION_MAJOR   0   )
set( CCOS_VERSION_MINOR   2   )
set( CCOS_VERSION_PATCH   0   )
set( CCOS_VERSION_BUILD   1   )

set( CCOS_VERSION_CMAKE     ${CCOS_VERSION_MAJOR}.${CCOS_VERSION_MINOR}.${CCOS_VERSION_PATCH})

set( PROJECT_DESCRIPTION    "Platform independant framework." )
