set(KERNEL_TYPE_HEADER
  Types/CcAppKnown.h
  Types/CcArguments.h
  Types/CcArray.h
  Types/CcBase.h
  Types/CcBaseSettings.h
  Types/CcBinaryStream.h
  Types/CcBitmap.h
  Types/CcBufferList.h
  Types/CcByteArray.h
  Types/CcColor.h
  Types/CcConfig.h
  Types/CcCoReferenceCount.h
  Types/CcDate.h
  Types/CcDateTime.h
  Types/CcGlobalStrings.h
  Types/CcGroup.h
  Types/CcGroupList.h
  Types/CcHandle.h
  Types/CcImageData.h
  Types/CcIp.h
  Types/CcList.h
  Types/CcListCommon.h
  Types/CcMap.h
  Types/CcMessageFormat.h
  Types/CcMapCommon.h
  Types/CcMutex.h
  Types/CcPair.h
  Types/CcPassword.h
  Types/CcPoint.h
  Types/CcRectangle.h
  Types/CcReferenceCount.h
  Types/CcRegEx.h
  Types/CcSharedPointer.h
  Types/CcSingleton.h
  Types/CcSize.h
  Types/CcSizeRelative.h
  Types/CcSmartPointer.h
  Types/CcStatic.h
  Types/CcStatus.h
  Types/CcString.h
  Types/CcStringList.h
  Types/CcStringStream.h
  Types/CcStringUtil.h
  Types/CcTable.h
  Types/CcTableRow.h
  Types/CcTree.h
  Types/CcTypes.h
  Types/CcUrl.h
  Types/CcUser.h
  Types/CcUserList.h
  Types/CcUuid.h
  Types/CcUuidKnown.h
  Types/CcVariant.h
  Types/CcVariantList.h
  Types/CcVector.h
  Types/CcVersion.h
  Types/CcVideoData.h
  Types/CcWString.h
  Types/IIo.h
)

set(KERNEL_TYPE_HASH_HEADER
  Types/Hash/CcAes.h
  Types/Hash/CcCrc32.h
  Types/Hash/CcHash.h
  Types/Hash/CcHmac.h
  Types/Hash/CcMd5.h
  Types/Hash/CcOtp.h
  Types/Hash/CcSqlEnDecode.h
  Types/Hash/CcSha1.h
  Types/Hash/CcSha256.h
  Types/Hash/IHash.h
)

set(KERNEL_TYPE_FILES
  ${KERNEL_TYPE_HEADER}
  ${KERNEL_TYPE_HASH_HEADER}
  Types/Hash/CcAes.cpp
  Types/Hash/CcCrc32.cpp
  Types/Hash/CcHash.cpp
  Types/Hash/CcHmac.cpp
  Types/Hash/CcMd5.cpp
  Types/Hash/CcOtp.cpp
  Types/Hash/CcSqlEnDecode.cpp
  Types/Hash/CcSha1.cpp
  Types/Hash/CcSha256.cpp
  Types/Hash/IHash.cpp
  
  Types/CcArguments.cpp
  Types/CcBinaryStream.cpp
  Types/CcBitmap.cpp
  Types/CcBufferList.cpp
  Types/CcByteArray.cpp
  Types/CcColor.cpp
  Types/CcConfig.cpp
  Types/CcCoReferenceCount.cpp
  Types/CcDate.cpp
  Types/CcDateTime.cpp
  Types/CcGlobalStrings.cpp
  Types/CcGroup.cpp
  Types/CcGroupList.cpp
  Types/CcImageData.cpp
  Types/CcIp.cpp
  Types/CcListCommon.cpp
  Types/CcMapCommon.cpp
  Types/CcMessageFormat.cpp
  Types/CcMutex.cpp
  Types/CcPassword.cpp
  Types/CcPoint.cpp
  Types/CcRectangle.cpp
  Types/CcReferenceCount.cpp
  Types/CcRegEx.cpp
  Types/CcSize.cpp
  Types/CcSizeRelative.cpp
  Types/CcStatic.cpp
  Types/CcStatus.cpp
  Types/CcString.cpp
  Types/CcStringList.cpp
  Types/CcStringStream.cpp
  Types/CcStringUtil.cpp
  Types/CcTable.cpp
  Types/CcTableRow.cpp
  Types/CcTree.cpp
  Types/CcTypes.cpp
  Types/CcUrl.cpp
  Types/CcUser.cpp
  Types/CcUserList.cpp
  Types/CcUuid.cpp
  Types/CcUuidKnown.cpp
  Types/CcVariant.cpp
  Types/CcVariantList.cpp
  Types/CcVersion.cpp
  Types/CcVideoData.cpp
  Types/CcWString.cpp
  Types/IIo.cpp
)
