TOOLS_DIR=$(pwd)
cd ..
cd ..
SOLUTION_POSTFIX=".Solution.ECL.STM3220EVAL"
TARGET_DIR=$(pwd)
TARGET_DIR_FIXED="$TARGET_DIR$SOLUTION_POSTFIX"

#rm -rf "$TARGET_DIR_FIXED"
mkdir "$TARGET_DIR_FIXED"
cd "$TARGET_DIR_FIXED"
cmake -G "Eclipse CDT4 - Unix Makefiles" "$TOOLS_DIR/../.." -DCMAKE_ECLIPSE_VERSION=4.9 -DCCOS_BOARD=CMakeConfig/Boards/STM3220GEVAL -DCMAKE_BUILD_TYPE=Debug
if [ $? -ne 0 ]
then
    exit -1
fi
