
ccflags-y := -fno-pie -DLINUXKERNEL -mcmodel=kernel -I"/home/coolcow/git/CcOS/CcKernelModule/../CcKernel/Types"

obj-m += CcKernelModuleLinux.o
CcKernelModuleLinux-y :=  CcKernelModuleLinux_main.o \
                          CcKernelModule.cpp.o \
                          CcMalloc.o
