if(WIN32)
  set( WORKING_DIR "${CC_CACHE_DIR}/Toolchains" )
  set( NINJA_DIR      "${WORKING_DIR}/Ninja" )
  set( NINJA_ZIP_FILE "${WORKING_DIR}/Ninja.zip")
  if(NOT EXISTS ${NINJA_DIR})
    if(NOT EXISTS ${NINJA_ZIP_FILE})
      message("- Download ninja")
      file( DOWNLOAD https://coolcow.de/projects/ThirdParty/Ninja/binaries/1.7.2.0/Ninja.zip 
            ${NINJA_ZIP_FILE}
            STATUS DOWNLOAD_STATUS)
      list(GET DOWNLOAD_STATUS 0 NUMERIC_STATUS)
      if(NOT ${NUMERIC_STATUS} EQUAL 0)
        file(REMOVE ${NINJA_ZIP_FILE})
        message(FATAL_ERROR "- Download result: ${DOWNLOAD_STATUS}")
      else()
        message("- Download succeeded")
      endif()    
    endif()
    
    if(EXISTS ${NINJA_ZIP_FILE})
      file(MAKE_DIRECTORY ${NINJA_DIR})
      execute_process(COMMAND ${CMAKE_COMMAND} -E tar xf ${NINJA_ZIP_FILE}
                      WORKING_DIRECTORY                  ${NINJA_DIR}
                      RESULT_VARIABLE NINJA_ZIP_FILE_EXTRACT_RESULT)
      if(${NINJA_ZIP_FILE_EXTRACT_RESULT} EQUAL 0)
        file(REMOVE ${NINJA_ZIP_FILE})
      else()
        file(REMOVE ${NINJA_ZIP_FILE})
        file(REMOVE_RECURSE ${NINJA_DIR})
        message(FATAL_ERROR "- Extract error: ${NINJA_ZIP_FILE}")
      endif()
    endif()
  else(NOT EXISTS ${NINJA_DIR})
    message("- Download ninja not required: ${NINJA_DIR}")       
  endif()
  set (CMAKE_MAKE_PROGRAM "${NINJA_DIR}/ninja.exe" PARENT_SCOPE)
  set (CMAKE_MAKE_PROGRAM "${NINJA_DIR}/ninja.exe")
  set(CMAKE_MAKE_PROGRAM   ${CMAKE_MAKE_PROGRAM} CACHE FILEPATH "" FORCE)
  message("- Ninja: ${CMAKE_MAKE_PROGRAM}")
endif()