if( WIN32 )
  message("-- Setup MinGW")
  set(CMAKE_C_COMPILER            C:/Tools/MinGW/bin/gcc.exe             CACHE INTERNAL "")
  set(CMAKE_CXX_COMPILER          C:/Tools/MinGW/bin/g++.exe             CACHE INTERNAL "")
  set(CMAKE_MAKE_PROGRAM          C:/Tools/MinGW/bin/mingw32-make.exe    CACHE INTERNAL "")
  set(ENV{PATH} "C:/Tools/MinGW/bin")
else()
  message(FATAL_ERROR "MinGW only available in Windows")
endif()
