# setup project root dir
set(CCOS_DIR ${CMAKE_CURRENT_LIST_DIR}/.. CACHE INTERNAL "")
set(CCOS_CONFIG_DIR ${CMAKE_CURRENT_LIST_DIR})
set(THIRDPARTY_DIR ${CMAKE_CURRENT_LIST_DIR}/../ThirdParty)

if(NOT EXISTS ${CCOS_CONFIG_DIR}/CcBuildConfig/CcBuildConfig.cmake)
  execute_process(COMMAND git submodule init "${CCOS_CONFIG_DIR}/CcBuildConfig"
          WORKING_DIRECTORY ${CMAKE_CURRENT_LIST_DIR})
  execute_process(COMMAND git submodule update "${CCOS_CONFIG_DIR}/CcBuildConfig"
          WORKING_DIRECTORY ${CMAKE_CURRENT_LIST_DIR})
endif()
include(${CCOS_CONFIG_DIR}/CcBuildConfig/CcBuildConfig.cmake)

################################################################################
# Load Macros from CcOS
################################################################################
include(${CCOS_CONFIG_DIR}/ProjectMacros.cmake )

set(CC_PROJECTS)

macro(CcOSLoadProjects)
  ################################################################################
  # Precheck all configurations and load thirdparty if required
  ################################################################################
  foreach(Project ${CC_PROJECTS})
    if(DEFINED CC_PROJECTS_${Project}_SYSTEM)
      foreach(System ${CC_PROJECTS_${Project}_SYSTEM})
        if(${System} STREQUAL "${CMAKE_SYSTEM_NAME}")
          add_subdirectory(${CC_PROJECTS_${Project}_PATH})
        endif()
      endforeach()
    else()
      add_subdirectory(${CC_PROJECTS_${Project}_PATH})
    endif()

  endforeach()
endmacro()

macro(CcAddProject ProjectName Relpath)
  set(DoAppend FALSE)
  set(oneValueArgs VERSION)
  set(multiValueArgs SYSTEM)
  cmake_parse_arguments(Project "" "${oneValueArgs}" "${multiValueArgs}" ${ARGN} )

  list(APPEND CC_PROJECTS ${ProjectName})
  set(CC_PROJECTS_${ProjectName}_PATH ${Relpath})
  if(DEFINED Project_SYSTEM)
    set(CC_PROJECTS_${ProjectName}_SYSTEM ${Project_SYSTEM})
  endif()
endmacro()

CcAddProject(CcAppInterfaces          CcAppInterfaces         SYSTEM Windows Linux Generic)
CcAddProject(CcBitcoin                CcBitcoin               SYSTEM Windows Linux Generic)
CcAddProject(CcDhcp                   CcDhcp                  SYSTEM Windows Linux Generic)
CcAddProject(CcDocuments              CcDocuments             SYSTEM Windows Linux Generic)
CcAddProject(CcFtp                    CcFtp                   SYSTEM Windows Linux Generic)
CcAddProject(CcHttp                   CcHttp                  SYSTEM Windows Linux Generic)
CcAddProject(CcKernel                 CcKernel                SYSTEM Windows Linux Generic)
CcAddProject(CcKernelModule           CcKernelModule          SYSTEM Windows Linux Generic)
CcAddProject(CcKernelModuleInterface  CcKernelModuleInterface SYSTEM Windows Linux Generic)
CcAddProject(CcMedia                  CcMedia                 SYSTEM Windows Linux Generic)
CcAddProject(CcModule                 CcModule                SYSTEM Windows Linux Generic)
CcAddProject(CcMqtt                   CcMqtt                  SYSTEM Windows Linux Generic)
CcAddProject(CcMtp                    CcMtp                   SYSTEM Windows Linux Generic)
CcAddProject(CcRemoteDevice           CcRemoteDevice          SYSTEM Windows Linux Generic)
CcAddProject(CcScpi                   CcScpi                  SYSTEM Windows Linux Generic)
CcAddProject(CcShell                  CcShell                 SYSTEM Windows Linux Generic)
CcAddProject(CcSql                    CcSql                   SYSTEM Windows Linux Generic)
CcAddProject(CcSsl                    CcSsl                   SYSTEM Windows Linux)
CcAddProject(CcTesting                CcTesting               SYSTEM Windows Linux Generic)
CcAddProject(CcTftp                   CcTftp                  SYSTEM Windows Linux Generic)
CcAddProject(CcConvert                Apps/CcConvert                SYSTEM Windows Linux)
CcAddProject(CcDhcpServer             Apps/CcDhcpServer             SYSTEM Windows Linux)
CcAddProject(CcFs                     Apps/CcFs                     SYSTEM Windows Linux)
CcAddProject(CcHash                   Apps/CcHash                   SYSTEM Windows Linux)
CcAddProject(CcKernelModuleTestDriver Apps/CcKernelModuleTestDriver SYSTEM Windows Linux)
CcAddProject(CcOSArgumentsApp         Apps/CcOSArgumentsApp         SYSTEM Windows Linux)
CcAddProject(CcOSModuleLoader         Apps/CcOSModuleLoader         SYSTEM Windows Linux)
CcAddProject(CcOSResourceApp          Apps/CcOSResourceApp          SYSTEM Windows Linux)
CcAddProject(CcRemoteDeviceClient     Apps/CcRemoteDeviceClient     SYSTEM Windows Linux)
CcAddProject(CcRemoteDeviceServer     Apps/CcRemoteDeviceServer     SYSTEM Windows Linux)
CcAddProject(CcScpiCli                Apps/CcScpiCli                SYSTEM Windows Linux)
CcAddProject(CcShellApp               Apps/CcShellApp               SYSTEM Windows Linux)
CcAddProject(CcUsbDriver              Apps/CcUsbDriver              SYSTEM Windows Linux)
CcAddProject(CcVDisk                  Apps/CcVDisk                  SYSTEM Windows Linux)
#CcAddProject(Raspbian                 Modules/Platform/Raspbian     )
CcAddProject(CcTestModule             Modules/CcTestModule    SYSTEM Windows Linux)
CcAddProject(openssl                  ThirdParty/openssl      SYSTEM Windows Linux)
CcAddProject(mtp                      ThirdParty/mtp          SYSTEM Windows Linux)
CcAddProject(sqlite3                  ThirdParty/sqlite3      SYSTEM Windows Linux)
CcAddProject(wiringPi                 ThirdParty/wiringPi     SYSTEM Windows Linux)