
if(WIN32)
  if(EXISTS "C:/Program Files/doxygen/bin/doxygen.exe")
    set(Doxygen_FOUND       TRUE)
    set(Doxygen_EXECUTABLE  "C:/Program Files/doxygen/bin/doxygen.exe")
  elseif(EXISTS "C:/Program Files (x86)/doxygen/bin/doxygen.exe")
    set(Doxygen_FOUND       TRUE)
    set(Doxygen_EXECUTABLE  "C:/Program Files (x86)/doxygen/bin/doxygen.exe")
  elseif(EXISTS "doxygen.exe")
    set(Doxygen_FOUND       TRUE)
    set(Doxygen_EXECUTABLE  "doxygen.exe")
  elseif(EXISTS "${CMAKE_CURRENT_LISTS_DIR}/doxygen.exe")
    set(Doxygen_FOUND       TRUE)
    set(Doxygen_EXECUTABLE  "${CMAKE_CURRENT_LISTS_DIR}/doxygen.exe")
  elseif(EXISTS "${CMAKE_CURRENT_BINARY_DIR}/doxygen.exe")
    set(Doxygen_FOUND       TRUE)
    set(Doxygen_EXECUTABLE  "${CMAKE_CURRENT_BINARY_DIR}/doxygen.exe")
  endif()
else()
  find_program(Doxygen doxygen)
  if(Doxygen)
    set(Doxygen_FOUND   TRUE)
    set(Doxygen_EXECUTABLE  "doxygen")
  endif()
endif()
