if(WIN32)
  set( WORKING_DIR "${CC_CACHE_DIR}/Toolchains" )
  set( MAKE_DIR      "${WORKING_DIR}/Cygwin" )
  set( MAKE_BINARY   "${WORKING_DIR}/Cygwin/bin/make")
  set( MAKE_ZIP_FILE "${WORKING_DIR}/Cygwin.zip")
  if(NOT EXISTS ${MAKE_DIR})
    if(NOT EXISTS ${MAKE_ZIP_FILE})
      message("- Download cygwin with make")
      file( DOWNLOAD https://coolcow.de/projects/ThirdParty/CygwinPackage/binaries/1.0.0.0/cygwin.32bit.7z
            ${MAKE_ZIP_FILE}
            STATUS DOWNLOAD_STATUS)
      list(GET DOWNLOAD_STATUS 0 NUMERIC_STATUS)
      if(NOT ${NUMERIC_STATUS} EQUAL 0)
        file(REMOVE ${MAKE_ZIP_FILE})
        message(FATAL_ERROR "- Download result: ${DOWNLOAD_STATUS}")
      else()
        message("- Download succeeded")
      endif()    
    endif()
    
    if(EXISTS ${MAKE_ZIP_FILE})
      file(MAKE_DIRECTORY ${MAKE_DIR})
      execute_process(COMMAND ${CMAKE_COMMAND} -E tar xf ${MAKE_ZIP_FILE}
                      WORKING_DIRECTORY                  ${MAKE_DIR}
                      RESULT_VARIABLE MAKE_ZIP_FILE_EXTRACT_RESULT)
      if(${MAKE_ZIP_FILE_EXTRACT_RESULT} EQUAL 0)
        file(REMOVE ${MAKE_ZIP_FILE})
      else()
        file(REMOVE ${MAKE_ZIP_FILE})
        file(REMOVE_RECURSE ${MAKE_DIR})
        message(FATAL_ERROR "- Extract error: ${MAKE_ZIP_FILE}")
      endif()
    endif()
  else(NOT EXISTS ${MAKE_DIR})
    message("- Download cygwin wit make not required: ${MAKE_DIR}")       
  endif()
  set(CMAKE_MAKE_PROGRAM "${MAKE_BINARY}" PARENT_SCOPE)
  set(CMAKE_MAKE_PROGRAM "${MAKE_BINARY}")
  set(CMAKE_MAKE_PROGRAM "${MAKE_BINARY}" CACHE FILEPATH "" FORCE)
  message("- make: ${CMAKE_MAKE_PROGRAM}")
endif()